name: "ntfy"
version: "1.0.4"
slug: "ntfy"
description: "Self-hosted ntfy notification server"
url: "https://docs.ntfy.sh/"
arch:
  - aarch64
  - amd64
  - armv7
startup: services
boot: auto
init: false
legacy: true
ports:
  80/tcp: 2586
ports_description:
  80/tcp: "ntfy web/API port"
map:
  - type: share
    read_only: false
options:
  base_url: "http://127.0.0.1:2586"
schema:
  base_url: url
  upstream_base_url: "url?"
